services:
  autobaomiguan:
    build: .
    image: autobaomiguan:latest
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - BM_DEBUG=1
      - BM_SSL_VERIFY=0
    restart: unless-stopped
